//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_14(void);
int64_t function_1b4(void);
int64_t function_244(void);
int64_t function_290(void);
int64_t function_31c(void);
int64_t function_40(void);
int64_t function_44(void);
int64_t function_e0(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(void) {
    // 0x40
    return function_40();
}

// Address range: 0x44 - 0xe0
int64_t function_44(void) {
    // 0x44
    return 0;
}

// Address range: 0xe0 - 0x1b4
int64_t function_e0(void) {
    // 0xe0
    int32_t v1; // 0xe0
    int32_t v2 = v1;
    int64_t v3; // 0xe0
    int32_t v4 = v3; // 0x164
    return (v2 + v4 + v1) * v4 - v2;
}

// Address range: 0x1b4 - 0x244
int64_t function_1b4(void) {
    // 0x1b4
    int64_t v1; // 0x1b4
    int64_t v2 = 508 * v1 * (v1 + 583); // 0x21c
    return (v2 + 508) * v2 + v1 & 0xffffffff;
}

// Address range: 0x244 - 0x290
int64_t function_244(void) {
    // 0x244
    return 498;
}

// Address range: 0x290 - 0x31c
int64_t function_290(void) {
    // 0x290
    int32_t v1; // 0x290
    return -0x1ead * v1;
}

// Address range: 0x31c - 0x4dc
int64_t function_31c(void) {
    // 0x31c
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

