//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t _24_d_1(void);
int64_t f_printf(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);
int64_t function_4e4(void);
int64_t function_4ec(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x10
int64_t f_printf(void) {
    // 0x0
    int64_t v1; // 0x0
    return v1 + 220;
}

// Address range: 0x14 - 0x2c
int64_t f_scanf_nop(void) {
    // 0x14
    return 220;
}

// Address range: 0x44 - 0x60
int64_t func0(void) {
    // 0x44
    int64_t result; // 0x44
    return result;
}

// Address range: 0xe0 - 0x120
int64_t func1(void) {
    // 0xe0
    _24_d_1();
    return 220;
}

// Address range: 0x1b4 - 0x1e4
int64_t func2(void) {
    // 0x1b4
    return 220;
}

// Address range: 0x244 - 0x260
int64_t func3(void) {
    // 0x244
    return 220;
}

// Address range: 0x290 - 0x2b0
int64_t func4(void) {
    // 0x290
    return 220;
}

// Address range: 0x31c - 0x344
int main(int argc, char ** argv) {
    // 0x31c
    return 220;
}

// Address range: 0x4dc - 0x4dd
int64_t _24_d_1(void) {
    // 0x4dc
    int64_t result; // 0x4dc
    return result;
}

// Address range: 0x4e4 - 0x4e5
int64_t function_4e4(void) {
    // 0x4e4
    int64_t result; // 0x4e4
    return result;
}

// Address range: 0x4ec - 0x4ed
int64_t function_4ec(void) {
    // 0x4ec
    int64_t result; // 0x4ec
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 11

