//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_1a0(void);
int64_t function_294(void);
int64_t function_30(void);
int64_t function_3a4(void);
int64_t function_4bc(void);
int64_t function_5d4(void);
int64_t function_60(void);
int64_t function_78(int64_t a1, int64_t a2);
int64_t function_8c(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x30
int64_t function_0(void) {
    // 0x0
    return 0;
}

// Address range: 0x30 - 0x60
int64_t function_30(void) {
    // 0x30
    int32_t v1; // 0x30
    return (uint32_t)v1;
}

// Address range: 0x60 - 0x78
int64_t function_60(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x1a0
int64_t function_8c(void) {
    // 0x8c
    function_30();
    function_30();
    int64_t v1 = function_60(); // 0xc0
    int64_t v2 = function_30(); // 0xc8
    int64_t v3 = function_60(); // 0xd0
    int64_t v4; // 0x8c
    return (v3 + v2 + 700 * (2 * v4 - v4 - v1)) * v3 + v2 & 0xffffffff;
}

// Address range: 0x1a0 - 0x294
int64_t function_1a0(void) {
    int64_t v1 = function_30(); // 0x1c4
    function_60();
    function_30();
    function_30();
    function_30();
    function_0();
    function_0();
    return v1 + 233 & 0xffffffff;
}

// Address range: 0x294 - 0x3a4
int64_t function_294(void) {
    int64_t v1 = function_60(); // 0x2b4
    int64_t v2 = function_60(); // 0x2bc
    int64_t v3 = function_30(); // 0x2c4
    int64_t v4 = function_30(); // 0x2cc
    function_60();
    function_0();
    function_0();
    return (v3 - v2 + -0xfffffd95 * v1 * v3) * v2 + v4 * (v2 + 0xfffffd95) & 0xffffffff;
}

// Address range: 0x3a4 - 0x4bc
int64_t function_3a4(void) {
    int32_t v1 = function_60(); // 0x3c8
    function_30();
    function_60();
    int64_t v2 = function_60(); // 0x3dc
    int32_t v3 = function_60(); // 0x3e8
    int32_t v4 = 737 * v1 + (int32_t)v2; // 0x40c
    function_0();
    function_0();
    function_0();
    return -94 * v3 * (v4 - v3 + v4 * v1) + v3;
}

// Address range: 0x4bc - 0x5d4
int64_t function_4bc(void) {
    // 0x4bc
    int64_t v1; // 0x4bc
    int32_t v2 = v1; // 0x4d8
    function_60();
    int64_t v3 = function_60(); // 0x4ec
    int64_t v4 = function_30(); // 0x4f4
    int32_t v5 = function_30(); // 0x500
    function_60();
    int32_t v6 = (int32_t)v3 - v2; // 0x524
    function_0();
    function_0();
    return v6 - ((int32_t)v4 + v2) + v5 + (v6 - 849) * v5;
}

// Address range: 0x5d4 - 0x668
int64_t function_5d4(void) {
    // 0x5d4
    function_30();
    function_30();
    function_30();
    function_30();
    function_8c();
    function_1a0();
    function_294();
    function_3a4();
    function_4bc();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

