//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t _24_d_1(void);
int64_t f_printf(void);
int64_t f_rand(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);
int64_t function_670(void);
int64_t function_78(int64_t a1, int64_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x20
int64_t f_printf(void) {
    // 0x0
    int64_t v1; // 0x0
    return v1 + 616;
}

// Address range: 0x30 - 0x48
int64_t f_scanf_nop(void) {
    // 0x30
    return 616;
}

// Address range: 0x60 - 0x6c
int64_t f_rand(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x1a0
int64_t func0(void) {
    // 0x8c
    f_scanf_nop();
    f_scanf_nop();
    int64_t v1 = f_rand(); // 0xc0
    int64_t v2 = f_scanf_nop(); // 0xc8
    int64_t v3 = f_rand(); // 0xd0
    int64_t v4; // 0x8c
    return (v3 + v2 + 700 * (2 * v4 - v4 - v1)) * v3 + v2 & 0xffffffff;
}

// Address range: 0x1a0 - 0x294
int64_t func1(void) {
    int64_t v1 = f_scanf_nop(); // 0x1c4
    f_rand();
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    f_printf();
    f_printf();
    return v1 + 233 & 0xffffffff;
}

// Address range: 0x294 - 0x3a4
int64_t func2(void) {
    int64_t v1 = f_rand(); // 0x2b4
    int64_t v2 = f_rand(); // 0x2bc
    int64_t v3 = f_scanf_nop(); // 0x2c4
    int64_t v4 = f_scanf_nop(); // 0x2cc
    f_rand();
    f_printf();
    f_printf();
    return (v3 - v2 + -0xfffffd95 * v1 * v3) * v2 + v4 * (v2 + 0xfffffd95) & 0xffffffff;
}

// Address range: 0x3a4 - 0x4bc
int64_t func3(void) {
    int32_t v1 = f_rand(); // 0x3c8
    f_scanf_nop();
    f_rand();
    int64_t v2 = f_rand(); // 0x3dc
    int32_t v3 = f_rand(); // 0x3e8
    int32_t v4 = 737 * v1 + (int32_t)v2; // 0x40c
    f_printf();
    f_printf();
    f_printf();
    return -94 * v3 * (v4 - v3 + v4 * v1) + v3;
}

// Address range: 0x4bc - 0x5d4
int64_t func4(void) {
    // 0x4bc
    int64_t v1; // 0x4bc
    int32_t v2 = v1; // 0x4d8
    f_rand();
    int64_t v3 = f_rand(); // 0x4ec
    int64_t v4 = f_scanf_nop(); // 0x4f4
    int32_t v5 = f_scanf_nop(); // 0x500
    f_rand();
    int32_t v6 = (int32_t)v3 - v2; // 0x524
    f_printf();
    f_printf();
    return v6 - ((int32_t)v4 + v2) + v5 + (v6 - 849) * v5;
}

// Address range: 0x5d4 - 0x668
int main(int argc, char ** argv) {
    // 0x5d4
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    func0();
    func1();
    func2();
    func3();
    func4();
    return 0;
}

// Address range: 0x668 - 0x669
int64_t _24_d_1(void) {
    // 0x668
    int64_t result; // 0x668
    return result;
}

// Address range: 0x670 - 0x671
int64_t function_670(void) {
    // 0x670
    int64_t result; // 0x670
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 12

