//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_14(void);
int64_t function_17c(void);
int64_t function_21c(void);
int64_t function_2f0(void);
int64_t function_398(void);
int64_t function_40(void);
int64_t function_44(void);
int64_t function_c4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(void) {
    // 0x40
    return function_40();
}

// Address range: 0x44 - 0xc4
int64_t function_44(void) {
    // 0x44
    int32_t v1; // 0x44
    int32_t v2 = v1;
    return v2 * v2 - v2;
}

// Address range: 0xc4 - 0x17c
int64_t function_c4(void) {
    // 0xc4
    int64_t v1; // 0xc4
    int32_t v2; // 0xc4
    return (int32_t)v1 - 12 + v2;
}

// Address range: 0x17c - 0x21c
int64_t function_17c(void) {
    // 0x17c
    int64_t v1; // 0x17c
    return 770 - v1 & 0xffffffff;
}

// Address range: 0x21c - 0x2f0
int64_t function_21c(void) {
    // 0x21c
    return 0;
}

// Address range: 0x2f0 - 0x398
int64_t function_2f0(void) {
    // 0x2f0
    int32_t v1; // 0x2f0
    return v1 - 676 - v1;
}

// Address range: 0x398 - 0x624
int64_t function_398(void) {
    // 0x398
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

