//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t f_printf(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x10
int64_t f_printf(void) {
    // 0x0
    return 0;
}

// Address range: 0x14 - 0x2c
int64_t f_scanf_nop(void) {
    // 0x14
    return 0;
}

// Address range: 0x44 - 0x64
int64_t func0(void) {
    // 0x44
    return 0;
}

// Address range: 0xc4 - 0x108
int64_t func1(void) {
    // 0xc4
    return 0;
}

// Address range: 0x17c - 0x1c4
int64_t func2(void) {
    // 0x17c
    return 0;
}

// Address range: 0x21c - 0x244
int64_t func3(void) {
    // 0x21c
    int64_t result; // 0x21c
    return result;
}

// Address range: 0x2f0 - 0x304
int64_t func4(void) {
    // 0x2f0
    int64_t result; // 0x2f0
    return result;
}

// Address range: 0x398 - 0x3c4
int main(int argc, char ** argv) {
    // 0x398
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

