//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t f_printf(void);
int64_t f_rand(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);
int64_t function_78(int64_t a1, int64_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x20
int64_t f_printf(void) {
    // 0x0
    return 0;
}

// Address range: 0x30 - 0x48
int64_t f_scanf_nop(void) {
    // 0x30
    return 0;
}

// Address range: 0x60 - 0x6c
int64_t f_rand(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x190
int64_t func0(void) {
    // 0x8c
    int64_t v1; // 0x8c
    int64_t v2 = v1;
    int64_t v3 = f_rand(); // 0xb0
    int64_t v4 = f_scanf_nop(); // 0xb8
    int64_t v5 = f_rand(); // 0xc0
    f_rand();
    int64_t v6 = f_rand(); // 0xd0
    f_printf();
    f_printf();
    f_printf();
    return (v2 - v4 + (v3 + v2 + v6) * v4) * v5 & 0xffffffff;
}

// Address range: 0x190 - 0x2d8
int64_t func1(void) {
    // 0x190
    int64_t v1; // 0x190
    int32_t v2 = v1; // 0x1a4
    int32_t v3 = f_scanf_nop(); // 0x1b4
    int32_t v4 = f_scanf_nop(); // 0x1bc
    int32_t v5 = f_rand(); // 0x1c4
    f_rand();
    int32_t v6 = f_rand(); // 0x1d4
    int32_t v7 = v5 * v3; // 0x1f0
    int32_t v8 = v7 + v4; // 0x200
    f_printf();
    f_printf();
    f_printf();
    return (v3 + v2 + v8) * v2 - v8 + (v5 + v4 + v6) * v6 * (v7 - v8 * v3) * v7;
}

// Address range: 0x2d8 - 0x3cc
int64_t func2(void) {
    // 0x2d8
    int64_t v1; // 0x2d8
    int32_t v2 = v1; // 0x2ec
    f_scanf_nop();
    f_rand();
    int32_t v3 = f_rand(); // 0x310
    int64_t v4 = f_rand(); // 0x314
    f_rand();
    int32_t v5 = v3 + 508; // 0x33c
    f_printf();
    int32_t v6 = ((int32_t)v1 + 583) * v2 * v5; // 0x37c
    return v2 - v3 - (int32_t)v4 + (v6 + v5) * v6;
}

// Address range: 0x3cc - 0x498
int64_t func3(void) {
    // 0x3cc
    f_scanf_nop();
    f_rand();
    f_scanf_nop();
    f_rand();
    return 498 - f_rand() & 0xffffffff;
}

// Address range: 0x498 - 0x588
int64_t func4(void) {
    // 0x498
    f_scanf_nop();
    int64_t v1 = f_scanf_nop(); // 0x4c0
    f_scanf_nop();
    f_scanf_nop();
    f_rand();
    f_printf();
    f_printf();
    return 0xffffe153 * v1 & 0xffffffff;
}

// Address range: 0x588 - 0x60c
int main(int argc, char ** argv) {
    // 0x588
    f_scanf_nop();
    f_rand();
    f_scanf_nop();
    f_rand();
    func0();
    func1();
    func2();
    func3();
    func4();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

