//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_190(void);
int64_t function_2d8(void);
int64_t function_30(void);
int64_t function_3cc(void);
int64_t function_498(void);
int64_t function_588(void);
int64_t function_60(void);
int64_t function_78(int64_t a1, int64_t a2);
int64_t function_8c(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x30
int64_t function_0(void) {
    // 0x0
    return 0;
}

// Address range: 0x30 - 0x60
int64_t function_30(void) {
    // 0x30
    int32_t v1; // 0x30
    return (uint32_t)v1;
}

// Address range: 0x60 - 0x78
int64_t function_60(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x190
int64_t function_8c(void) {
    // 0x8c
    int64_t v1; // 0x8c
    int64_t v2 = v1;
    int64_t v3 = function_60(); // 0xb0
    int64_t v4 = function_30(); // 0xb8
    int64_t v5 = function_60(); // 0xc0
    function_60();
    int64_t v6 = function_60(); // 0xd0
    function_0();
    function_0();
    function_0();
    return (v2 - v4 + (v3 + v2 + v6) * v4) * v5 & 0xffffffff;
}

// Address range: 0x190 - 0x2d8
int64_t function_190(void) {
    // 0x190
    int64_t v1; // 0x190
    int32_t v2 = v1; // 0x1a4
    int32_t v3 = function_30(); // 0x1b4
    int32_t v4 = function_30(); // 0x1bc
    int32_t v5 = function_60(); // 0x1c4
    function_60();
    int32_t v6 = function_60(); // 0x1d4
    int32_t v7 = v5 * v3; // 0x1f0
    int32_t v8 = v7 + v4; // 0x200
    function_0();
    function_0();
    function_0();
    return (v3 + v2 + v8) * v2 - v8 + (v5 + v4 + v6) * v6 * (v7 - v8 * v3) * v7;
}

// Address range: 0x2d8 - 0x3cc
int64_t function_2d8(void) {
    // 0x2d8
    int64_t v1; // 0x2d8
    int32_t v2 = v1; // 0x2ec
    function_30();
    function_60();
    int32_t v3 = function_60(); // 0x310
    int64_t v4 = function_60(); // 0x314
    function_60();
    int32_t v5 = v3 + 508; // 0x33c
    function_0();
    int32_t v6 = ((int32_t)v1 + 583) * v2 * v5; // 0x37c
    return v2 - v3 - (int32_t)v4 + (v6 + v5) * v6;
}

// Address range: 0x3cc - 0x498
int64_t function_3cc(void) {
    // 0x3cc
    function_30();
    function_60();
    function_30();
    function_60();
    return 498 - function_60() & 0xffffffff;
}

// Address range: 0x498 - 0x588
int64_t function_498(void) {
    // 0x498
    function_30();
    int64_t v1 = function_30(); // 0x4c0
    function_30();
    function_30();
    function_60();
    function_0();
    function_0();
    return 0xffffe153 * v1 & 0xffffffff;
}

// Address range: 0x588 - 0x60c
int64_t function_588(void) {
    // 0x588
    function_30();
    function_60();
    function_30();
    function_60();
    function_8c();
    function_190();
    function_2d8();
    function_3cc();
    function_498();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

