//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t f_printf(void);
int64_t f_rand(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);
int64_t function_78(int64_t a1, int64_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x20
int64_t f_printf(void) {
    // 0x0
    return 0;
}

// Address range: 0x30 - 0x48
int64_t f_scanf_nop(void) {
    // 0x30
    return 0;
}

// Address range: 0x60 - 0x6c
int64_t f_rand(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x1b4
int64_t func0(void) {
    int64_t v1 = f_rand(); // 0xac
    f_scanf_nop();
    f_rand();
    int64_t v2 = f_rand(); // 0xc4
    int64_t v3 = f_rand(); // 0xcc
    f_printf();
    f_printf();
    f_printf();
    f_printf();
    int64_t v4; // 0x8c
    return 2 * (v1 - v4 + 0xfffffe20 * v3) - v2 & 0xffffffff;
}

// Address range: 0x1b4 - 0x2a4
int64_t func1(void) {
    // 0x1b4
    int64_t v1; // 0x1b4
    int64_t v2 = v1;
    int64_t v3 = f_scanf_nop(); // 0x1d4
    int64_t v4 = f_rand(); // 0x1dc
    int64_t v5 = f_scanf_nop(); // 0x1e4
    int64_t v6 = f_scanf_nop(); // 0x1ec
    f_rand();
    f_printf();
    return v6 * v2 - (v3 + v2 - v5 + v6) * v4 & 0xffffffff;
}

// Address range: 0x2a4 - 0x3b8
int64_t func2(void) {
    // 0x2a4
    f_scanf_nop();
    f_rand();
    int64_t v1 = f_scanf_nop(); // 0x2d0
    int32_t v2 = f_scanf_nop(); // 0x2dc
    int32_t v3 = -296 * (int32_t)f_rand(); // 0x300
    f_printf();
    return (v2 + 759 + v3) * v3 * (-759 - (int32_t)v1 + v2 - v3);
}

// Address range: 0x3b8 - 0x4c8
int64_t func3(void) {
    // 0x3b8
    f_scanf_nop();
    f_rand();
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    f_printf();
    f_printf();
    f_printf();
    int64_t v1; // 0x3b8
    return v1 + 0xfffffba2 & 0xffffffff;
}

// Address range: 0x4c8 - 0x5c4
int64_t func4(void) {
    // 0x4c8
    int64_t v1; // 0x4c8
    int64_t v2 = v1;
    f_scanf_nop();
    int64_t v3 = f_rand(); // 0x4f4
    int64_t v4 = f_rand(); // 0x4fc
    f_rand();
    f_scanf_nop();
    return 0xfffffd61 * v2 * v3 + v2 - v4 & 0xffffffff;
}

// Address range: 0x5c4 - 0x644
int main(int argc, char ** argv) {
    // 0x5c4
    f_rand();
    f_scanf_nop();
    f_rand();
    f_rand();
    func0();
    func1();
    func2();
    func3();
    func4();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

