//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_1b4(void);
int64_t function_2a4(void);
int64_t function_30(void);
int64_t function_3b8(void);
int64_t function_4c8(void);
int64_t function_5c4(void);
int64_t function_60(void);
int64_t function_78(int64_t a1, int64_t a2);
int64_t function_8c(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x30
int64_t function_0(void) {
    // 0x0
    return 0;
}

// Address range: 0x30 - 0x60
int64_t function_30(void) {
    // 0x30
    int32_t v1; // 0x30
    return (uint32_t)v1;
}

// Address range: 0x60 - 0x78
int64_t function_60(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x1b4
int64_t function_8c(void) {
    int64_t v1 = function_60(); // 0xac
    function_30();
    function_60();
    int64_t v2 = function_60(); // 0xc4
    int64_t v3 = function_60(); // 0xcc
    function_0();
    function_0();
    function_0();
    function_0();
    int64_t v4; // 0x8c
    return 2 * (v1 - v4 + 0xfffffe20 * v3) - v2 & 0xffffffff;
}

// Address range: 0x1b4 - 0x2a4
int64_t function_1b4(void) {
    // 0x1b4
    int64_t v1; // 0x1b4
    int64_t v2 = v1;
    int64_t v3 = function_30(); // 0x1d4
    int64_t v4 = function_60(); // 0x1dc
    int64_t v5 = function_30(); // 0x1e4
    int64_t v6 = function_30(); // 0x1ec
    function_60();
    function_0();
    return v6 * v2 - (v3 + v2 - v5 + v6) * v4 & 0xffffffff;
}

// Address range: 0x2a4 - 0x3b8
int64_t function_2a4(void) {
    // 0x2a4
    function_30();
    function_60();
    int64_t v1 = function_30(); // 0x2d0
    int32_t v2 = function_30(); // 0x2dc
    int32_t v3 = -296 * (int32_t)function_60(); // 0x300
    function_0();
    return (v2 + 759 + v3) * v3 * (-759 - (int32_t)v1 + v2 - v3);
}

// Address range: 0x3b8 - 0x4c8
int64_t function_3b8(void) {
    // 0x3b8
    function_30();
    function_60();
    function_30();
    function_30();
    function_30();
    function_0();
    function_0();
    function_0();
    int64_t v1; // 0x3b8
    return v1 + 0xfffffba2 & 0xffffffff;
}

// Address range: 0x4c8 - 0x5c4
int64_t function_4c8(void) {
    // 0x4c8
    int64_t v1; // 0x4c8
    int64_t v2 = v1;
    function_30();
    int64_t v3 = function_60(); // 0x4f4
    int64_t v4 = function_60(); // 0x4fc
    function_60();
    function_30();
    return 0xfffffd61 * v2 * v3 + v2 - v4 & 0xffffffff;
}

// Address range: 0x5c4 - 0x644
int64_t function_5c4(void) {
    // 0x5c4
    function_60();
    function_30();
    function_60();
    function_60();
    function_8c();
    function_1b4();
    function_2a4();
    function_3b8();
    function_4c8();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

