//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_114(void);
int64_t function_14(void);
int64_t function_188(void);
int64_t function_230(void);
int64_t function_2a4(void);
int64_t function_40(int64_t a1);
int64_t function_44(void);
int64_t function_88(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(int64_t a1) {
    // 0x40
    return function_40(a1);
}

// Address range: 0x44 - 0x88
int64_t function_44(void) {
    // 0x44
    function_14();
    int64_t v1 = function_14(); // 0x54
    function_14();
    int64_t v2 = function_14(); // 0x60
    function_14();
    function_0();
    return v2 * v1 - v2 & 0xffffffff;
}

// Address range: 0x88 - 0x114
int64_t function_88(void) {
    // 0x88
    int64_t v1; // 0x88
    int64_t v2 = function_40(function_40(v1)); // 0xa0
    int64_t v3 = function_14(); // 0xa8
    int64_t v4 = function_14(); // 0xb0
    int64_t v5 = function_40(v4); // 0xb8
    function_0();
    function_0();
    function_0();
    return v2 + 0xfffffff4 + v3 - v5 + (v4 + v2) * v5 & 0xffffffff;
}

// Address range: 0x114 - 0x188
int64_t function_114(void) {
    // 0x114
    function_14();
    int64_t v1 = function_40(function_14()); // 0x13c
    function_40(function_40(v1));
    function_0();
    function_0();
    function_0();
    int64_t v2; // 0x114
    return 770 - v2 & 0xffffffff;
}

// Address range: 0x188 - 0x230
int64_t function_188(void) {
    // 0x188
    int64_t v1; // 0x188
    int64_t v2 = function_40(v1); // 0x1ac
    int64_t v3 = function_40(function_40(v2)); // 0x1b8
    int64_t v4 = function_40(v3); // 0x1c0
    function_14();
    function_0();
    function_0();
    function_0();
    function_0();
    function_0();
    return v3 - v4 & 0xffffffff;
}

// Address range: 0x230 - 0x2a4
int64_t function_230(void) {
    // 0x230
    int64_t v1; // 0x230
    int64_t v2 = function_40(v1); // 0x240
    int64_t v3 = function_40(v2); // 0x248
    int64_t v4 = function_14(); // 0x250
    function_14();
    int64_t v5 = function_14(); // 0x25c
    function_0();
    function_0();
    return 0xfffffd5c - v2 + v3 - v4 + v5 & 0xffffffff;
}

// Address range: 0x2a4 - 0x308
int64_t function_2a4(void) {
    // 0x2a4
    function_14();
    function_40(function_14());
    function_14();
    function_44();
    function_88();
    function_114();
    function_188();
    function_230();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

