//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_14(void);
int64_t function_154(void);
int64_t function_1bc(void);
int64_t function_240(void);
int64_t function_290(void);
int64_t function_40(int64_t a1);
int64_t function_44(void);
int64_t function_e4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(int64_t a1) {
    // 0x40
    return function_40(a1);
}

// Address range: 0x44 - 0xe4
int64_t function_44(void) {
    // 0x44
    int64_t v1; // 0x44
    int64_t v2 = function_40(v1); // 0x5c
    int64_t v3 = function_14(); // 0x64
    int64_t v4 = function_40(function_40(v3)); // 0x70
    int64_t v5 = function_40(v4); // 0x78
    function_0();
    function_0();
    function_0();
    function_0();
    return 2 * (v2 - v1 + 0x1fffffe20 * v5) - v4 & 0xffffffff;
}

// Address range: 0xe4 - 0x154
int64_t function_e4(void) {
    // 0xe4
    int64_t v1; // 0xe4
    int64_t v2 = v1;
    int64_t v3 = function_14(); // 0xfc
    int64_t v4 = function_40(v3); // 0x104
    int64_t v5 = function_14(); // 0x10c
    int64_t v6 = function_14(); // 0x114
    function_40(v6);
    function_0();
    return v6 * v2 - (v3 + v2 - v5 + v6) * v4 & 0xffffffff;
}

// Address range: 0x154 - 0x1bc
int64_t function_154(void) {
    // 0x154
    function_40(function_14());
    int64_t v1 = function_14(); // 0x16c
    int64_t v2 = function_14(); // 0x174
    int64_t v3 = 0xfffffed8 * function_40(v2); // 0x184
    function_0();
    return (v2 + 759 + v3) * v3 * (0xfffffd09 - v1 + v2 - v3) & 0xfffffff8;
}

// Address range: 0x1bc - 0x240
int64_t function_1bc(void) {
    // 0x1bc
    function_40(function_14());
    function_14();
    function_14();
    function_14();
    function_0();
    function_0();
    function_0();
    int64_t v1; // 0x1bc
    return v1 + 0xfffffba2 & 0xffffffff;
}

// Address range: 0x240 - 0x290
int64_t function_240(void) {
    // 0x240
    int64_t v1; // 0x240
    int64_t v2 = v1;
    int64_t v3 = function_40(function_14()); // 0x258
    int64_t v4 = function_40(v3); // 0x260
    function_40(v4);
    function_14();
    return 0xfffffd61 * v2 * v3 + v2 - v4 & 0xffffffff;
}

// Address range: 0x290 - 0x2e8
int64_t function_290(void) {
    // 0x290
    int64_t v1; // 0x290
    function_40(v1);
    int64_t v2 = function_14(); // 0x2a4
    function_40(function_40(v2));
    function_44();
    function_e4();
    function_154();
    function_1bc();
    function_240();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

