//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t f_printf(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x10
int64_t f_printf(void) {
    // 0x0
    return 0;
}

// Address range: 0x14 - 0x2c
int64_t f_scanf_nop(void) {
    // 0x14
    return 0;
}

// Address range: 0x44 - 0xe4
int64_t func0(void) {
    // 0x44
    int64_t v1; // 0x44
    int64_t v2 = rand(v1); // 0x5c
    int64_t v3 = rand(rand(f_scanf_nop())); // 0x70
    int64_t v4 = rand(v3); // 0x78
    f_printf();
    f_printf();
    f_printf();
    f_printf();
    return 2 * (v2 - v1 + 0x1fffffe20 * v4) - v3 & 0xffffffff;
}

// Address range: 0xe4 - 0x154
int64_t func1(void) {
    // 0xe4
    int64_t v1; // 0xe4
    int64_t v2 = v1;
    int64_t v3 = f_scanf_nop(); // 0xfc
    int64_t v4 = rand(v3); // 0x104
    int64_t v5 = f_scanf_nop(); // 0x10c
    int64_t v6 = f_scanf_nop(); // 0x114
    rand(v6);
    f_printf();
    return v6 * v2 - (v3 + v2 - v5 + v6) * v4 & 0xffffffff;
}

// Address range: 0x154 - 0x1bc
int64_t func2(void) {
    // 0x154
    rand(f_scanf_nop());
    int64_t v1 = f_scanf_nop(); // 0x16c
    int64_t v2 = f_scanf_nop(); // 0x174
    int64_t v3 = 0xfffffed8 * rand(v2); // 0x184
    f_printf();
    return (v2 + 759 + v3) * v3 * (0xfffffd09 - v1 + v2 - v3) & 0xfffffff8;
}

// Address range: 0x1bc - 0x240
int64_t func3(void) {
    // 0x1bc
    rand(f_scanf_nop());
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    f_printf();
    f_printf();
    f_printf();
    int64_t v1; // 0x1bc
    return v1 + 0xfffffba2 & 0xffffffff;
}

// Address range: 0x240 - 0x290
int64_t func4(void) {
    // 0x240
    int64_t v1; // 0x240
    int64_t v2 = v1;
    int64_t v3 = rand(f_scanf_nop()); // 0x258
    int64_t v4 = rand(v3); // 0x260
    rand(v4);
    f_scanf_nop();
    return 0xfffffd61 * v2 * v3 + v2 - v4 & 0xffffffff;
}

// Address range: 0x290 - 0x2e8
int main(int argc, char ** argv) {
    // 0x290
    rand(argc);
    rand(rand(f_scanf_nop()));
    func0();
    func1();
    func2();
    func3();
    func4();
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int64_t rand(int64_t a1);

// --------------------- Meta-Information ---------------------

// Detected functions: 8

