//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_104(void);
int64_t function_14(void);
int64_t function_178(void);
int64_t function_1fc(void);
int64_t function_27c(void);
int64_t function_40(int64_t a1);
int64_t function_44(void);
int64_t function_a4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(int64_t a1) {
    // 0x40
    return function_40(a1);
}

// Address range: 0x44 - 0xa4
int64_t function_44(void) {
    // 0x44
    function_14();
    int64_t v1 = function_40(function_14()); // 0x64
    int64_t v2 = function_14(); // 0x6c
    int64_t v3 = function_40(v2); // 0x74
    int64_t v4; // 0x44
    return (v3 + v2 + 700 * (2 * v4 - v4 - v1)) * v3 + v2 & 0xffffffff;
}

// Address range: 0xa4 - 0x104
int64_t function_a4(void) {
    int64_t v1 = function_14(); // 0xb8
    function_40(v1);
    function_14();
    function_14();
    function_14();
    function_0();
    function_0();
    return v1 + 233 & 0xffffffff;
}

// Address range: 0x104 - 0x178
int64_t function_104(void) {
    // 0x104
    int64_t v1; // 0x104
    int64_t v2 = function_40(v1); // 0x114
    int64_t v3 = function_40(v2); // 0x11c
    int64_t v4 = function_14(); // 0x124
    int64_t v5 = function_14(); // 0x12c
    function_40(v5);
    function_0();
    function_0();
    return (v4 - v3 + -0xfffffd95 * v2 * v4) * v3 + v5 * (v3 + 0xfffffd95) & 0xffffffff;
}

// Address range: 0x178 - 0x1fc
int64_t function_178(void) {
    // 0x178
    int64_t v1; // 0x178
    int64_t v2 = function_40(v1); // 0x18c
    int64_t v3 = function_14(); // 0x194
    int64_t v4 = function_40(function_40(v3)); // 0x1a4
    int64_t v5 = function_40(v4); // 0x1ac
    int64_t v6 = v4 + 737 * v2; // 0x1b4
    function_0();
    function_0();
    function_0();
    return 0xffffffa2 * v5 * (v6 - v5 + v6 * v2) + v5 & 0xffffffff;
}

// Address range: 0x1fc - 0x27c
int64_t function_1fc(void) {
    // 0x1fc
    int64_t v1; // 0x1fc
    int64_t v2 = function_40(function_40(v1)); // 0x21c
    int64_t v3 = function_14(); // 0x224
    int64_t v4 = function_14(); // 0x22c
    function_40(v4);
    int64_t v5 = v2 - v1; // 0x238
    function_0();
    function_0();
    return v5 - (v3 + v1) + v4 + (v5 + 0xfffffcaf) * v4 & 0xffffffff;
}

// Address range: 0x27c - 0x2e8
int64_t function_27c(void) {
    // 0x27c
    function_14();
    function_14();
    function_14();
    function_14();
    function_44();
    function_a4();
    function_104();
    function_178();
    function_1fc();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

