//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t f_printf(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x10
int64_t f_printf(void) {
    // 0x0
    return 0;
}

// Address range: 0x14 - 0x2c
int64_t f_scanf_nop(void) {
    // 0x14
    return 0;
}

// Address range: 0x44 - 0xa4
int64_t func0(void) {
    // 0x44
    f_scanf_nop();
    int64_t v1 = rand(f_scanf_nop()); // 0x64
    int64_t v2 = f_scanf_nop(); // 0x6c
    int64_t v3 = rand(v2); // 0x74
    int64_t v4; // 0x44
    return (v3 + v2 + 700 * (2 * v4 - v4 - v1)) * v3 + v2 & 0xffffffff;
}

// Address range: 0xa4 - 0x104
int64_t func1(void) {
    int64_t v1 = f_scanf_nop(); // 0xb8
    rand(v1);
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    f_printf();
    f_printf();
    return v1 + 233 & 0xffffffff;
}

// Address range: 0x104 - 0x178
int64_t func2(void) {
    // 0x104
    int64_t v1; // 0x104
    int64_t v2 = rand(v1); // 0x114
    int64_t v3 = rand(v2); // 0x11c
    int64_t v4 = f_scanf_nop(); // 0x124
    int64_t v5 = f_scanf_nop(); // 0x12c
    rand(v5);
    f_printf();
    f_printf();
    return (v4 - v3 + -0xfffffd95 * v2 * v4) * v3 + v5 * (v3 + 0xfffffd95) & 0xffffffff;
}

// Address range: 0x178 - 0x1fc
int64_t func3(void) {
    // 0x178
    int64_t v1; // 0x178
    int64_t v2 = rand(v1); // 0x18c
    int64_t v3 = rand(rand(f_scanf_nop())); // 0x1a4
    int64_t v4 = rand(v3); // 0x1ac
    int64_t v5 = v3 + 737 * v2; // 0x1b4
    f_printf();
    f_printf();
    f_printf();
    return 0xffffffa2 * v4 * (v5 - v4 + v5 * v2) + v4 & 0xffffffff;
}

// Address range: 0x1fc - 0x27c
int64_t func4(void) {
    // 0x1fc
    int64_t v1; // 0x1fc
    int64_t v2 = rand(rand(v1)); // 0x21c
    int64_t v3 = f_scanf_nop(); // 0x224
    int64_t v4 = f_scanf_nop(); // 0x22c
    rand(v4);
    int64_t v5 = v2 - v1; // 0x238
    f_printf();
    f_printf();
    return v5 - (v3 + v1) + v4 + (v5 + 0xfffffcaf) * v4 & 0xffffffff;
}

// Address range: 0x27c - 0x2e8
int main(int argc, char ** argv) {
    // 0x27c
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    f_scanf_nop();
    func0();
    func1();
    func2();
    func3();
    func4();
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int64_t rand(int64_t a1);

// --------------------- Meta-Information ---------------------

// Detected functions: 8

