//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_14(void);
int64_t function_164(void);
int64_t function_208(void);
int64_t function_2b0(void);
int64_t function_358(void);
int64_t function_40(void);
int64_t function_44(void);
int64_t function_cc(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(void) {
    // 0x40
    return function_40();
}

// Address range: 0x44 - 0xcc
int64_t function_44(void) {
    // 0x44
    int32_t v1; // 0x44
    return (uint32_t)v1;
}

// Address range: 0xcc - 0x164
int64_t function_cc(void) {
    // 0xcc
    int32_t v1; // 0xcc
    return v1 + 233;
}

// Address range: 0x164 - 0x208
int64_t function_164(void) {
    // 0x164
    int32_t v1; // 0x164
    int32_t v2 = v1;
    int64_t v3; // 0x164
    int32_t v4 = v3; // 0x180
    return (v2 - v4 + 619 * v4 * v2) * v4 + (v4 - 619) * v1;
}

// Address range: 0x208 - 0x2b0
int64_t function_208(void) {
    // 0x208
    return 0;
}

// Address range: 0x2b0 - 0x358
int64_t function_2b0(void) {
    // 0x2b0
    int32_t v1; // 0x2b0
    int32_t v2 = v1;
    int32_t v3 = 0; // 0x328
    int64_t v4; // 0x2b0
    return v2 - (int32_t)v4 + v3 - v1 + (v3 - 849) * v2;
}

// Address range: 0x358 - 0x554
int64_t function_358(void) {
    // 0x358
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

