//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t f_printf(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x10
int64_t f_printf(void) {
    // 0x0
    return 0;
}

// Address range: 0x14 - 0x2c
int64_t f_scanf_nop(void) {
    // 0x14
    return 0;
}

// Address range: 0x44 - 0x7c
int64_t func0(void) {
    // 0x44
    return 0;
}

// Address range: 0xcc - 0xf4
int64_t func1(void) {
    // 0xcc
    return 0;
}

// Address range: 0x164 - 0x17c
int64_t func2(void) {
    // 0x164
    int64_t result; // 0x164
    return result;
}

// Address range: 0x208 - 0x220
int64_t func3(void) {
    // 0x208
    int64_t result; // 0x208
    return result;
}

// Address range: 0x2b0 - 0x2d0
int64_t func4(void) {
    // 0x2b0
    int64_t result; // 0x2b0
    return result;
}

// Address range: 0x358 - 0x380
int main(int argc, char ** argv) {
    // 0x358
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

