//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t _24_d_1(void);
int64_t f_printf(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);
int64_t function_504(void);
int64_t function_50c(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x10
int64_t f_printf(void) {
    // 0x0
    int64_t v1; // 0x0
    return v1 + 252;
}

// Address range: 0x14 - 0x2c
int64_t f_scanf_nop(void) {
    // 0x14
    return 252;
}

// Address range: 0x44 - 0x60
int64_t func0(void) {
    // 0x44
    int64_t result; // 0x44
    return result;
}

// Address range: 0x10c - 0x138
int64_t func1(void) {
    // 0x10c
    return 252;
}

// Address range: 0x1a8 - 0x1d0
int64_t func2(void) {
    // 0x1a8
    return 252;
}

// Address range: 0x244 - 0x26c
int64_t func3(void) {
    // 0x244
    return 252;
}

// Address range: 0x304 - 0x32c
int64_t func4(void) {
    // 0x304
    return 252;
}

// Address range: 0x374 - 0x38c
int main(int argc, char ** argv) {
    // 0x374
    return argc;
}

// Address range: 0x4fc - 0x4fd
int64_t _24_d_1(void) {
    // 0x4fc
    int64_t result; // 0x4fc
    return result;
}

// Address range: 0x504 - 0x505
int64_t function_504(void) {
    // 0x504
    int64_t result; // 0x504
    return result;
}

// Address range: 0x50c - 0x50d
int64_t function_50c(void) {
    // 0x50c
    int64_t result; // 0x50c
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 11

