//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_10c(void);
int64_t function_14(void);
int64_t function_1a8(void);
int64_t function_244(void);
int64_t function_304(void);
int64_t function_374(void);
int64_t function_40(void);
int64_t function_44(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(void) {
    // 0x40
    return function_40();
}

// Address range: 0x44 - 0x10c
int64_t function_44(void) {
    // 0x44
    return 0;
}

// Address range: 0x10c - 0x1a8
int64_t function_10c(void) {
    // 0x10c
    int64_t v1; // 0x10c
    int32_t v2; // 0x10c
    return v2 * (int32_t)v1;
}

// Address range: 0x1a8 - 0x244
int64_t function_1a8(void) {
    // 0x1a8
    return 0;
}

// Address range: 0x244 - 0x304
int64_t function_244(void) {
    // 0x244
    int64_t v1; // 0x244
    return v1 + 0xfffffba2 & 0xffffffff;
}

// Address range: 0x304 - 0x374
int64_t function_304(void) {
    // 0x304
    int64_t v1; // 0x304
    return v1 & 0xffffffff;
}

// Address range: 0x374 - 0x4fc
int64_t function_374(void) {
    // 0x374
    function_244();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

