//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t _24_d_1(void);
int64_t f_printf(void);
int64_t f_rand(void);
int64_t f_scanf_nop(void);
int64_t func0(void);
int64_t func1(void);
int64_t func2(void);
int64_t func3(void);
int64_t func4(void);
int64_t function_61c(void);
int64_t function_78(int64_t a1, int64_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x20
int64_t f_printf(void) {
    // 0x0
    int64_t v1; // 0x0
    return v1 + 532;
}

// Address range: 0x30 - 0x48
int64_t f_scanf_nop(void) {
    // 0x30
    return 532;
}

// Address range: 0x60 - 0x6c
int64_t f_rand(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x160
int64_t func0(void) {
    // 0x8c
    f_scanf_nop();
    int64_t v1 = f_scanf_nop(); // 0xb0
    f_scanf_nop();
    int64_t v2 = f_scanf_nop(); // 0xc0
    f_scanf_nop();
    f_printf();
    return v2 * v1 - v2 & 0xffffffff;
}

// Address range: 0x160 - 0x27c
int64_t func1(void) {
    // 0x160
    f_rand();
    int64_t v1 = f_rand(); // 0x18c
    int64_t v2 = f_scanf_nop(); // 0x194
    int64_t v3 = f_scanf_nop(); // 0x19c
    int64_t v4 = f_rand(); // 0x1a4
    f_printf();
    f_printf();
    f_printf();
    return v1 + 0xfffffff4 + v2 - v4 + (v3 + v1) * v4 & 0xffffffff;
}

// Address range: 0x27c - 0x368
int64_t func2(void) {
    // 0x27c
    f_scanf_nop();
    f_scanf_nop();
    f_rand();
    f_rand();
    f_rand();
    f_printf();
    f_printf();
    f_printf();
    int64_t v1; // 0x27c
    return 770 - v1 & 0xffffffff;
}

// Address range: 0x368 - 0x490
int64_t func3(void) {
    // 0x368
    f_rand();
    f_rand();
    int64_t v1 = f_rand(); // 0x3a0
    int64_t v2 = f_rand(); // 0x3a8
    f_scanf_nop();
    f_printf();
    f_printf();
    f_printf();
    f_printf();
    f_printf();
    return v1 - v2 & 0xffffffff;
}

// Address range: 0x490 - 0x58c
int64_t func4(void) {
    int64_t v1 = f_rand(); // 0x4ac
    int64_t v2 = f_rand(); // 0x4b4
    int64_t v3 = f_scanf_nop(); // 0x4bc
    f_scanf_nop();
    int64_t v4 = f_scanf_nop(); // 0x4cc
    f_printf();
    f_printf();
    return 0xfffffd5c - v1 + v2 - v3 + v4 & 0xffffffff;
}

// Address range: 0x58c - 0x614
int main(int argc, char ** argv) {
    // 0x58c
    f_scanf_nop();
    f_scanf_nop();
    f_rand();
    f_scanf_nop();
    func0();
    func1();
    func2();
    func3();
    func4();
    return 0;
}

// Address range: 0x614 - 0x615
int64_t _24_d_1(void) {
    // 0x614
    int64_t result; // 0x614
    return result;
}

// Address range: 0x61c - 0x61d
int64_t function_61c(void) {
    // 0x61c
    int64_t result; // 0x61c
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 12

