//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_160(void);
int64_t function_27c(void);
int64_t function_30(void);
int64_t function_368(void);
int64_t function_490(void);
int64_t function_58c(void);
int64_t function_60(void);
int64_t function_78(int64_t a1, int64_t a2);
int64_t function_8c(void);

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x30
int64_t function_0(void) {
    // 0x0
    return 0;
}

// Address range: 0x30 - 0x60
int64_t function_30(void) {
    // 0x30
    int32_t v1; // 0x30
    return (uint32_t)v1;
}

// Address range: 0x60 - 0x78
int64_t function_60(void) {
    // 0x60
    int64_t result; // 0x60
    return result;
}

// Address range: 0x78 - 0x8c
int64_t function_78(int64_t a1, int64_t a2) {
    // 0x78
    int64_t v1; // 0x78
    *(int32_t *)(v1 - 4) = (int32_t)v1;
    return v1 & 0xffffffff;
}

// Address range: 0x8c - 0x160
int64_t function_8c(void) {
    // 0x8c
    function_30();
    int64_t v1 = function_30(); // 0xb0
    function_30();
    int64_t v2 = function_30(); // 0xc0
    function_30();
    function_0();
    return v2 * v1 - v2 & 0xffffffff;
}

// Address range: 0x160 - 0x27c
int64_t function_160(void) {
    // 0x160
    function_60();
    int64_t v1 = function_60(); // 0x18c
    int64_t v2 = function_30(); // 0x194
    int64_t v3 = function_30(); // 0x19c
    int64_t v4 = function_60(); // 0x1a4
    function_0();
    function_0();
    function_0();
    return v1 + 0xfffffff4 + v2 - v4 + (v3 + v1) * v4 & 0xffffffff;
}

// Address range: 0x27c - 0x368
int64_t function_27c(void) {
    // 0x27c
    function_30();
    function_30();
    function_60();
    function_60();
    function_60();
    function_0();
    function_0();
    function_0();
    int64_t v1; // 0x27c
    return 770 - v1 & 0xffffffff;
}

// Address range: 0x368 - 0x490
int64_t function_368(void) {
    // 0x368
    function_60();
    function_60();
    int64_t v1 = function_60(); // 0x3a0
    int64_t v2 = function_60(); // 0x3a8
    function_30();
    function_0();
    function_0();
    function_0();
    function_0();
    function_0();
    return v1 - v2 & 0xffffffff;
}

// Address range: 0x490 - 0x58c
int64_t function_490(void) {
    int64_t v1 = function_60(); // 0x4ac
    int64_t v2 = function_60(); // 0x4b4
    int64_t v3 = function_30(); // 0x4bc
    function_30();
    int64_t v4 = function_30(); // 0x4cc
    function_0();
    function_0();
    return 0xfffffd5c - v1 + v2 - v3 + v4 & 0xffffffff;
}

// Address range: 0x58c - 0x614
int64_t function_58c(void) {
    // 0x58c
    function_30();
    function_30();
    function_60();
    function_30();
    function_8c();
    function_160();
    function_27c();
    function_368();
    function_490();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

