//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t function_0(void);
int64_t function_14(void);
int64_t function_164(void);
int64_t function_1d8(int64_t a1);
int64_t function_204(void);
int64_t function_258(void);
int64_t function_40(int64_t a1);
int64_t function_44(void);
int64_t function_bc(void);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x0 - 0x14
int64_t function_0(void) {
    while (true) {
        // continue -> 0x10
    }
}

// Address range: 0x14 - 0x40
int64_t function_14(void) {
    // 0x14
    int32_t v1; // 0x14
    return (uint32_t)v1;
}

// Address range: 0x40 - 0x44
int64_t function_40(int64_t a1) {
    // 0x40
    return function_40(a1);
}

// Address range: 0x44 - 0xbc
int64_t function_44(void) {
    // 0x44
    int64_t v1; // 0x44
    int64_t v2 = v1;
    int64_t v3 = function_40(v2); // 0x5c
    int64_t v4 = function_14(); // 0x64
    int64_t v5 = function_40(v4); // 0x6c
    int64_t v6 = function_40(function_40(v5)); // 0x78
    function_0();
    function_0();
    function_0();
    return (v2 - v4 + (v3 + v2 + v6) * v4) * v5 & 0xffffffff;
}

// Address range: 0xbc - 0x164
int64_t function_bc(void) {
    // 0xbc
    int64_t v1; // 0xbc
    int64_t v2 = v1;
    int64_t v3 = function_14(); // 0xd8
    int64_t v4 = function_14(); // 0xe0
    int64_t v5 = function_40(v4); // 0xe8
    int64_t v6 = function_40(function_40(v5)); // 0xf4
    int64_t v7 = v5 * v3; // 0xf8
    int64_t v8 = v7 + v4; // 0xfc
    function_0();
    function_0();
    function_0();
    return (v3 + v2 + v8) * v2 - v8 + v6 * v7 * (v5 + v4 + v6) * (v7 - v8 * v3) & 0xffffffff;
}

// Address range: 0x164 - 0x1d8
int64_t function_164(void) {
    int64_t v1 = function_14(); // 0x180
    int64_t v2 = function_40(function_40(v1)); // 0x188
    int64_t v3 = function_40(v2); // 0x190
    function_40(v3);
    int64_t v4 = v2 + 508; // 0x19c
    function_0();
    int64_t v5; // 0x164
    int64_t v6 = (v5 + 583) * v5 * v4; // 0x1c4
    return v5 - v2 - v3 + (v6 + v4) * v6 & 0xffffffff;
}

// Address range: 0x1d8 - 0x204
int64_t function_1d8(int64_t a1) {
    // 0x1d8
    function_40(function_14());
    int64_t v1 = function_40(function_14()); // 0x1ec
    return 498 - function_40(v1) & 0xffffffff;
}

// Address range: 0x204 - 0x258
int64_t function_204(void) {
    // 0x204
    function_14();
    int64_t v1 = function_14(); // 0x218
    function_14();
    function_40(function_14());
    function_0();
    function_0();
    return 0xffffe153 * v1 & 0xffffffff;
}

// Address range: 0x258 - 0x2b0
int64_t function_258(void) {
    // 0x258
    function_40(function_14());
    function_40(function_14());
    function_44();
    function_bc();
    function_164();
    function_1d8((int64_t)&g1);
    function_204();
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

